// const name = 1;
// let name1 = "string";
// let name2 = true;
// let name3 = false;
// let name4 = null;
// let name5 = underfined;
// var name2 = 3;

// name = "salut";
// name1 = "salut"


// console.log(name);
// console.log(name1);
// let score = null;



// let ion = 2 ,
//  vasea =4;
// console.log (ion+vasea);
// score= ion+vasea;
// console.log(typeof ion);

// const nume = "Popil";
// const prenume = "Laura";
// console.log(nume +"  "+ prenume);

// let a = "text";
// let b = 4;
// console.log(a +"  "+ b);
// let.score = null;
// console.log(score);
// let ion = 
alert("salut")
prompt("salut cum te numesti")